
default: &default
  adapter: postgresql
  encoding: unicode
  # username: rails
  # password: qwerty7

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: elevator_platform_development

 
test:
  <<: *default
  database: elevator_platform_test


production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>

